apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dotnet-basic-axjcrisw-gitops
  description: This is GitOps manifest for dotnet-basic-axjcrisw   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=dotnet-basic-axjcrisw
    backstage.io/kubernetes-id: dotnet-basic-axjcrisw 
    backstage.io/techdocs-ref: dir:.
    dev.azure.com/project: shared-public
    dev.azure.com/build-definition: dotnet-basic-axjcrisw-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:dotnet-basic-axjcrisw
